Repository softeerbootcamp4th/Team9-Podo-BE, pull requests merged in 2024-08, with the labels that each got.

#41 [Feature] 유형검사 결과 확인/제출 로직 분리 및 공유 링크 생성 api 추가
  build.gradle
  script/start.sh
  src/main/java/com/softeer/podo/admin/model/entity/LotsUser.java
  src/main/java/com/softeer/podo/admin/repository/LotsUserRepository.java
  src/main/java/com/softeer/podo/common/response/ErrorCode.java
  src/main/java/com/softeer/podo/common/utils/AESUtils.java
  src/main/java/com/softeer/podo/common/utils/URLUtils.java
  src/main/java/com/softeer/podo/event/controller/EventLotsApiController.java
  src/main/java/com/softeer/podo/event/controller/EventLotsController.java
  src/main/java/com/softeer/podo/event/controller/EventLotsPageController.java
  src/main/java/com/softeer/podo/event/exception/AESExecutionException.java
  src/main/java/com/softeer/podo/event/exception/EventExceptionHandler.java
  src/main/java/com/softeer/podo/event/exception/InvalidResultTypeException.java
  src/main/java/com/softeer/podo/event/exception/LotsShareLinkNotExistsException.java
  src/main/java/com/softeer/podo/event/model/dto/LotsApplicationRequestDto.java
  src/main/java/com/softeer/podo/event/model/dto/LotsApplicationResponseDto.java
  src/main/java/com/softeer/podo/event/model/dto/LotsTypeRequestDto.java
  src/main/java/com/softeer/podo/event/model/dto/LotsTypeResponseDto.java
  src/main/java/com/softeer/podo/event/model/dto/ScenarioDto.java
  src/main/java/com/softeer/podo/event/model/dto/mapper/LotsEventMapper.java
  src/main/java/com/softeer/podo/event/model/entity/LotsShareLink.java
  src/main/java/com/softeer/podo/event/model/entity/TestResult.java
  src/main/java/com/softeer/podo/event/repository/LotsShareLinkRepository.java
  src/main/java/com/softeer/podo/event/service/EventLotsService.java
  src/main/java/com/softeer/podo/event/util/Result.java
  src/main/java/com/softeer/podo/event/util/SelectionMap.java
  src/main/resources/application.yml
  src/main/resources/templates/error/404.html
  src/main/resources/templates/type/adventurer.html
  src/main/resources/templates/type/best_driver.html
  src/main/resources/templates/type/early_adopter.html
  src/main/resources/templates/type/trendsetter.html
  src/test/java/com/softeer/podo/admin/service/AdminServiceTest.java
Labels: enhancement

#53 [Feature] 어드민 로깅 추가
  src/main/java/com/softeer/podo/common/utils/AESUtils.java
  src/main/java/com/softeer/podo/common/utils/JsonUtils.java
  src/main/java/com/softeer/podo/common/utils/MdcUtils.java
  src/main/java/com/softeer/podo/common/utils/UrlUtils.java
  src/main/java/com/softeer/podo/config/FilterConfig.java
  src/main/java/com/softeer/podo/event/service/EventLotsService.java
  src/main/java/com/softeer/podo/log/aop/AdminLogAspect.java
  src/main/java/com/softeer/podo/log/filter/RequestCollectionFilter.java
  src/main/java/com/softeer/podo/log/filter/RequestWrapper.java
  src/main/java/com/softeer/podo/log/model/dto/RequestInfoDto.java
  src/main/java/com/softeer/podo/log/model/entity/AdminLog.java
  src/main/java/com/softeer/podo/log/repository/AdminLogRepository.java
  src/main/java/com/softeer/podo/log/service/AdminLogService.java
Labels: enhancement

#57 [Feat] url parameter를 이용한 조건부 페이징 추가
  src/main/java/com/softeer/podo/admin/controller/AdminController.java
  src/main/java/com/softeer/podo/admin/service/AdminService.java
  src/main/java/com/softeer/podo/event/repository/ArrivalUserRepository.java
  src/main/java/com/softeer/podo/event/repository/LotsUserRepository.java
Labels: enhancement

#56 [Feat] 어드민 로깅 조회 API 추가 및 코드 리팩토링
  src/main/java/com/softeer/podo/admin/controller/AdminController.java
  src/main/java/com/softeer/podo/admin/model/dto/AdminLogDto.java
  src/main/java/com/softeer/podo/admin/model/dto/response/GetAdminLogListResponseDto.java
  src/main/java/com/softeer/podo/common/utils/AESUtils.java
  src/main/java/com/softeer/podo/common/utils/JsonUtils.java
  src/main/java/com/softeer/podo/common/utils/MdcUtils.java
  src/main/java/com/softeer/podo/log/aop/AdminLogAspect.java
  src/main/java/com/softeer/podo/log/filter/RequestCollectionFilter.java
  src/main/java/com/softeer/podo/log/filter/RequestWrapper.java
  src/main/java/com/softeer/podo/log/mapper/AdminLogMapper.java
  src/main/java/com/softeer/podo/log/service/AdminLogService.java
  src/main/java/com/softeer/podo/security/jwt/ExceptionHandleFilter.java
  src/main/java/com/softeer/podo/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/softeer/podo/security/jwt/TokenProvider.java
  src/main/java/com/softeer/podo/verification/facade/VerificationFacade.java
  src/main/java/com/softeer/podo/verification/service/MessageService.java
  src/main/java/com/softeer/podo/verification/service/RedisService.java
  src/main/java/com/softeer/podo/verification/service/VerificationService.java
Labels: enhancement, fixup

#60 [Feature] result id를 이용하여 드라이버 유형 반환하는 api 추가
  src/main/java/com/softeer/podo/event/controller/EventLotsApiController.java
  src/main/java/com/softeer/podo/event/model/dto/request/LotsTypeByIdRequestDto.java
  src/main/java/com/softeer/podo/event/service/EventLotsService.java
Labels: enhancement

#64 [Feature] 파일 S3 업로드 추가, 필터에서 Multipart 데이터를 받기 위한 ServletRequest Wrapping
  build.gradle
  src/main/java/com/softeer/podo/admin/controller/AdminController.java
  src/main/java/com/softeer/podo/admin/exception/AdminExceptionHandler.java
  src/main/java/com/softeer/podo/admin/exception/S3RegisterFailureException.java
  src/main/java/com/softeer/podo/admin/model/dto/request/ConfigEventRequestDto.java
  src/main/java/com/softeer/podo/admin/service/AdminService.java
  src/main/java/com/softeer/podo/common/response/ErrorCode.java
  src/main/java/com/softeer/podo/common/utils/RequestUtils.java
  src/main/java/com/softeer/podo/common/utils/S3Utils.java
  src/main/java/com/softeer/podo/config/FilterConfig.java
  src/main/java/com/softeer/podo/config/S3Config.java
  src/main/java/com/softeer/podo/event/model/entity/Event.java
  src/main/java/com/softeer/podo/log/filter/Info.java
  src/main/java/com/softeer/podo/log/filter/RequestJsonBodyCollectionFilter.java
  src/main/java/com/softeer/podo/log/filter/RequestMultipartBodyCollectionFilter.java
  src/main/java/com/softeer/podo/log/filter/RequestWrapper.java
  src/main/java/com/softeer/podo/log/model/entity/AdminLog.java
  src/main/resources/application.yml
  src/test/java/com/softeer/podo/admin/controller/AdminControllerTest.java
  src/test/java/com/softeer/podo/admin/service/AdminServiceTest.java
  src/test/resources/application.yml
Labels: enhancement

#69 [Feature] 메시지 전송방식 수정
  src/main/java/com/softeer/podo/PodoApplication.java
  src/main/java/com/softeer/podo/verification/controller/VerificationController.java
  src/main/java/com/softeer/podo/verification/facade/VerificationFacade.java
  src/main/java/com/softeer/podo/verification/service/MessageReleaseService.java
  src/main/java/com/softeer/podo/verification/service/MessageService.java
Labels: fixup

#63 [Fix] 공유링크가 FE의 공유 결과 페이지에 직접 연결되도록 수정 및 공유링크 redirection api 기능 변경
  src/main/java/com/softeer/podo/event/controller/EventLotsPageController.java
  src/main/java/com/softeer/podo/event/service/EventLotsService.java
Labels: enhancement, fixup

#70 [Fix] 로깅 조건 수정
  src/main/java/com/softeer/podo/log/filter/RequestWrapper.java
Labels: fixup

#68 [Fix] cors 에러 해결 및 https 연결 추가
  src/main/java/com/softeer/podo/PodoApplication.java
  src/main/resources/application.yml
Labels: enhancement, fixup

#71 [Fix] https 설정 제거
  src/main/java/com/softeer/podo/PodoApplication.java
  src/main/resources/application.yml
Labels: fixup
